version: "2"
services:
  rucio02.pic.es:
    build:
      context: .
      dockerfile: DockerFiles/Docker-server-pic
    hostname: rucio02.pic.es 
    restart: always
    ports:
      - "443:443"
    links:
      - ruciodb:ruciodb
      - graphite:graphite
      - ftsdb:ftsdb
      - minio:minio
      - activemq:activemq
      - kibana:kibana
      - grafana:grafan
      - rucio-client-1:rucio-client-1
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
      - ./daemon_logs:/var/log/daemon_logs
      - /etc/grid-security/certificates:/etc/grid-security/certificates
    environment:
      - X509_USER_CERT=/etc/grid-security/usercert.pem
      - X509_USER_KEY=/etc/grid-security/userkey.pem
    entrypoint: /usr/bin/yes
  ruciodb:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off", "-c","max_connections=5000"]
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "81:81"
  ftsdb:
    image: mysql:5
    hostname: ftsdb
    restart: always
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
    ports:
      - "3306:3306"
  minio:
    image: minio/minio
    hostname: minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    ports:
      - "9000:9000"
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key
    command: ["server", "/data"]
  activemq:
    image: webcenter/activemq:latest
    hostname: activemq
    restart: always
    environment:
       - ACTIVEMQ_CONFIG_NAME=activemq
       - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
       - ACTIVEMQ_USERS_hermes=supersecret
       - ACTIVEMQ_GROUPS_writes=hermes
       - ACTIVEMQ_USERS_logstash=supersecret
       - ACTIVEMQ_GROUPS_reads=logstash
       - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
    ports:
      - "61613:61613"
      - "8161:8161"
  elasticsearch:
    image: elasticsearch:7.4.0
    hostname: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.2
    hostname: logstash
    restart: always
    command: bash -c "logstash-plugin install logstash-input-stomp ; /usr/local/bin/docker-entrypoint"
    ports:
      - "5044:5044"
    links:
      - "activemq:activemq"
      - "elasticsearch:elasticsearch"
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
  kibana:
    image: kibana:7.4.0
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - "elasticsearch:elasticsearch"
  rucio-client-1:
    build:
      context: .
      dockerfile: DockerFiles/rucio-client-1-pic
    hostname: rucio-client-1
    restart: always
    ports:
      - "1096:1096"
    volumes:
      - /etc/grid-security/certificates:/etc/grid-security/certificates
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
    entrypoint: /usr/bin/yes
