version: "2"
services:
  rucio.pic.testserver:
    build:
      context: .
      dockerfile: DockerFiles/Docker-server
    hostname: rucio.pic.testserver
    restart: always
    ports:
      - "443:443"
    links:
      - ruciodb:ruciodb
      - graphite:graphite
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
      - ./daemon_logs:/var/log/daemon_logs
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
    command: ["/monit-entrypoint.sh"]
  ruciodb:
    image: postgres:11
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off"]
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
