version: "2"
services:
  rucio:
    build:
      context: .
      dockerfile: DockerFiles/Docker-server
    hostname: rucio
    restart: always
    ports:
      - "443:443"
    links:
      - ruciodb:ruciodb
      - graphite:graphite
      - fts:fts
      - ftsdb:ftsdb
      - xrd1:xrd1
      - xrd2:xrd2
      - xrd3:xrd3
      - minio:minio
      - activemq:activemq
      - kibana:kibana
      - grafana:grafana
      - rucio-client-1:rucio-client-1
      - rucio-client-2:rucio-client-2
      - rucio-client-3:rucio-client-3
      - rucio-client-4:rucio-client-4
      - rucio-client-5:rucio-client-5
      - rucio-client-6:rucio-client-6
    volumes:
      - ../../../tools:/opt/rucio/tools
      - ../../../bin:/opt/rucio/bin
      - ../../../lib:/opt/rucio/lib
      - ./daemon_logs:/var/log/daemon_logs
    environment:
      - X509_USER_CERT=/opt/rucio/etc/usercert.pem
      - X509_USER_KEY=/opt/rucio/etc/userkey.pem
    command: ["/monit-entrypoint.sh"]
  ruciodb:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_USER=rucio
      - POSTGRES_DB=rucio
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
    command: ["-c", "fsync=off","-c", "synchronous_commit=off","-c", "full_page_writes=off", "-c","max_connections=1000"]
  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "80:80"
  fts:
    image: rucio/fts
    hostname: fts
    restart: always
    ports:
      - "8446:8446"
      - "8449:8449"
  ftsdb:
    image: mysql:5
    hostname: ftsdb
    restart: always
    environment:
      - MYSQL_USER=fts
      - MYSQL_PASSWORD=fts
      - MYSQL_ROOT_PASSWORD=fts
      - MYSQL_DATABASE=fts
    ports:
      - "3306:3306"
  xrd1:
    image: rucio/xrootd
    hostname: xrd1
    restart: always
    environment:
      - XRDPORT=1094
    ports:
      - "1094:1094"
    volumes:
      - ../../certs/hostcert_xrd1.pem:/tmp/xrdcert.pem
      - ../../certs/hostcert_xrd1.key.pem:/tmp/xrdkey.pem
  xrd2:
    image: rucio/xrootd
    hostname: xrd2
    restart: always
    environment:
      - XRDPORT=1095
    ports:
      - "1095:1095"
    volumes:
      - ../../certs/hostcert_xrd2.pem:/tmp/xrdcert.pem
      - ../../certs/hostcert_xrd2.key.pem:/tmp/xrdkey.pem
  minio:
    image: minio/minio
    hostname: minio
    restart: always
    environment:
      - MINIO_ACCESS_KEY=admin
      - MINIO_SECRET_KEY=password
    ports:
      - "9000:9000"
    volumes:
      - ../../certs/hostcert_minio.pem:/root/.minio/certs/public.crt
      - ../../certs/hostcert_minio.key.pem:/root/.minio/certs/private.key
    command: ["server", "/data"]
  activemq:
    image: webcenter/activemq:latest
    hostname: activemq
    restart: always
    environment:
       - ACTIVEMQ_CONFIG_NAME=activemq
       - ACTIVEMQ_CONFIG_DEFAULTACCOUNT=false
       - ACTIVEMQ_USERS_hermes=supersecret
       - ACTIVEMQ_GROUPS_writes=hermes
       - ACTIVEMQ_USERS_logstash=supersecret
       - ACTIVEMQ_GROUPS_reads=logstash
       - ACTIVEMQ_CONFIG_SCHEDULERENABLED=true
    ports:
      - "61613:61613"
      - "8161:8161"
  elasticsearch:
    image: elasticsearch:7.4.0
    hostname: elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.3.2
    hostname: logstash
    restart: always
    command: bash -c "logstash-plugin install logstash-input-stomp ; /usr/local/bin/docker-entrypoint"
    ports:
      - "5044:5044"
    links:
      - "activemq:activemq"
      - "elasticsearch:elasticsearch"
    volumes:
      - ./pipeline.conf:/usr/share/logstash/pipeline/pipeline.conf
  kibana:
    image: kibana:7.4.0
    hostname: kibana
    restart: always
    ports:
      - "5601:5601"
    links:
      - "elasticsearch:elasticsearch"
  grafana:
    image: grafana/grafana:latest
    hostname: grafana
    restart: always
    ports:
      - "3000:3000"
    links:
      - "elasticsearch:elasticsearch"
  rucio-client-1:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-1
    hostname: rucio-client-1
    restart: always
    ports:
      - "1096:1096"
    environment:
      - X509_USER_CERT=/opt/rucio/etc/ruciouser.pem
      - X509_USER_KEY=/opt/rucio/etc/ruciouser.key.pem
    entrypoint: /usr/bin/yes
  rucio-client-2:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-2
    hostname: rucio-client-2
    restart: always
    ports:
      - "1097:1097"
    environment:
      - X509_USER_CERT=/opt/rucio/etc/ruciouser.pem
      - X509_USER_KEY=/opt/rucio/etc/ruciouser.key.pem
    entrypoint: /usr/bin/yes
  xrd3:
    image: rucio/xrootd-noauth
    hostname: xrd3
    restart: always
    environment:
      - XRDPORT=1095
    ports:
      - "1099:1099"
    volumes:
      - ../../certs/hostcert_xrd3.pem:/tmp/xrdcert.pem
      - ../../certs/hostcert_xrd3.key.pem:/tmp/xrdkey.pem
  rucio-client-3:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-3
    hostname: rucio-client-3
    restart: always
    ports:
      - "1100:1100"
    environment:
      - X509_USER_CERT=/opt/rucio/etc/mariouser.pem
      - X509_USER_KEY=/opt/rucio/etc/mariouser.key.pem
    entrypoint: /usr/bin/yes
  rucio-client-4:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-4
    hostname: rucio-client-4
    restart: always
    ports:
      - "1101:1101"
    environment:
      - X509_USER_CERT=/opt/rucio/etc/gonzalouser.pem
      - X509_USER_KEY=/opt/rucio/etc/gonzalouser.key.pem
    entrypoint: /usr/bin/yes
  rucio-client-5:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-5
    hostname: rucio-client-5
    restart: always
    ports:
      - "1102:1102"
  rucio-client-6:
    build:
      context: .
      dockerfile: DockerFiles/Docker-client-6
    hostname: rucio-client-6
    restart: always
    ports:
      - "1103:1103"
    environment:
      - X509_USER_CERT=/opt/rucio/etc/pauuser.pem
      - X509_USER_KEY=/opt/rucio/etc/pauuser.key.pem
    entrypoint: /usr/bin/yes
